T_max: 64
a2a_radius: 150
accelerator: gpu
devices: 1
dropout: 0.1
head_dim: 16
hidden_dim: 128
homogenizing: true
input_dim: 2
load_samples: false
lr: 0.0005
max_epochs: 64
num_denoiser_layers: 2
num_encoder_layers: 1
num_freq_bands: 64
num_future_steps: 60
num_heads: 8
num_workers: 8
persistent_workers: true
pin_memory: true
pl2a_radius: 150
pl2pl_radius: 150
pred_deg: 6
root: data/datasets
shuffle: true
space_dim: 2
test_batch_size: 32
test_processed_dir: data/datasets/test_A2_processed/
test_raw_dir: null
train_batch_size: 32
train_processed_dir: data/datasets/train_A2_processed/
train_raw_dir: null
val_batch_size: 32
val_processed_dir: data/datasets/val_A2_processed/
val_raw_dir: null
weight_decay: 0.0
